# Generated by Django 2.0.5 on 2018-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userset',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
